apiVersion: v2
name: tailscale
description: A Helm chart for Tailscale
type: application
version: 0.1.0
appVersion: "unstable"

dependencies:
  - name: tailscale-operator
    condition: tailscale-operator.enabled
    repository: https://pkgs.tailscale.com/helmcharts
    version: 1.90.6
