longhorn:
  enabled: true
  global:
    nodeSelector:
      longhorn.io/node: "true"

  defaultSettings:
    defaultDataPath: "/var/lib/longhorn"
    systemManagedComponentsNodeSelector: "longhorn.io/node=true"

  longhornUI:
    replicas: 1
